# Generating Training Data
The data I have is spread around multiple CSV files. This notebook will be used to combine the data from the multiple files into a (m,22,9) as the dataset features for players and a (m, 2, 1) array with the target labels. The steps will include:

1. Getting matches played no later than 1970
2. For each match
    i. Get players from home team
    ii. Get players from away team
    iii. Combine two lists into players
    iv. For each player
        a. Get statistics at that point
    v. Store players in feature array
    vi. Store match result in target array
3. Save features and target array

Depending on the number of matches, I will use batching.

In [69]:
# Imports
import pandas as pd
import numpy as np
import numpy.typing as npt
import math
from datetime import datetime

In [2]:
# Get matches after 1970
matches = pd.read_csv("matches.csv")
matches.head()

,key_id,tournament_id,tournament_name,match_id,match_name,stage_name,group_name,group_stage,knockout_stage,replayed,...,away_team_score_margin,extra_time,penalty_shootout,score_penalties,home_team_score_penalties,away_team_score_penalties,result,home_team_win,away_team_win,draw
0,1,WC-1930,1930 FIFA World Cup,M-1930-01,France v Mexico,group stage,Group 1,1,0,0,...,-3,0,0,0-0,0,0,home team win,1,0,0
1,2,WC-1930,1930 FIFA World Cup,M-1930-02,United States v Belgium,group stage,Group 4,1,0,0,...,-3,0,0,0-0,0,0,home team win,1,0,0
2,3,WC-1930,1930 FIFA World Cup,M-1930-03,Yugoslavia v Brazil,group stage,Group 2,1,0,0,...,-1,0,0,0-0,0,0,home team win,1,0,0
3,4,WC-1930,1930 FIFA World Cup,M-1930-04,Romania v Peru,group stage,Group 3,1,0,0,...,-2,0,0,0-0,0,0,home team win,1,0,0
4,5,WC-1930,1930 FIFA World Cup,M-1930-05,Argentina v France,group stage,Group 1,1,0,0,...,-1,0,0,0-0,0,0,home team win,1,0,0

In [3]:
# Explore what's in the dataset
matches.columns

Index(['key_id', 'tournament_id', 'tournament_name', 'match_id', 'match_name',
       'stage_name', 'group_name', 'group_stage', 'knockout_stage', 'replayed',
       'replay', 'match_date', 'match_time', 'stadium_id', 'stadium_name',
       'city_name', 'country_name', 'home_team_id', 'home_team_name',
       'home_team_code', 'away_team_id', 'away_team_name', 'away_team_code',
       'score', 'home_team_score', 'away_team_score', 'home_team_score_margin',
       'away_team_score_margin', 'extra_time', 'penalty_shootout',
       'score_penalties', 'home_team_score_penalties',
       'away_team_score_penalties', 'result', 'home_team_win', 'away_team_win',
       'draw'],
      dtype='str')

In [20]:
reduced_matches = matches[['match_id', 'tournament_id', 'home_team_id', 'away_team_id', 'home_team_score', 'away_team_score']]
reduced_matches.head()

,match_id,tournament_id,home_team_id,away_team_id,home_team_score,away_team_score
0,M-1930-01,WC-1930,T-28,T-44,4,1
1,M-1930-02,WC-1930,T-79,T-06,3,0
2,M-1930-03,WC-1930,T-83,T-09,2,1
3,M-1930-04,WC-1930,T-58,T-54,3,1
4,M-1930-05,WC-1930,T-03,T-28,1,0

In [21]:
# Extract year from tournamet_id
reduced_matches['year'] = reduced_matches['tournament_id'].apply(lambda x: int(x.split("-")[-1]))
reduced_matches.head()

,match_id,tournament_id,home_team_id,away_team_id,home_team_score,away_team_score,year
0,M-1930-01,WC-1930,T-28,T-44,4,1,1930
1,M-1930-02,WC-1930,T-79,T-06,3,0,1930
2,M-1930-03,WC-1930,T-83,T-09,2,1,1930
3,M-1930-04,WC-1930,T-58,T-54,3,1,1930
4,M-1930-05,WC-1930,T-03,T-28,1,0,1930

In [22]:
reduced_matches = reduced_matches.drop('tournament_id', axis=1)
reduced_matches.head()

    match_id home_team_id away_team_id  home_team_score  away_team_score  year
0  M-1930-01         T-28         T-44                4                1  1930
1  M-1930-02         T-79         T-06                3                0  1930
2  M-1930-03         T-83         T-09                2                1  1930
3  M-1930-04         T-58         T-54                3                1  1930
4  M-1930-05         T-03         T-28                1                0  1930

In [24]:
matches_later_1970 =reduced_matches[reduced_matches['year'] >= 1970]
matches_later_1970.head()

,match_id,home_team_id,away_team_id,home_team_score,away_team_score,year
200,M-1970-01,T-44,T-69,0,0,1970
201,M-1970-02,T-80,T-38,2,0,1970
202,M-1970-03,T-27,T-58,1,0,1970
203,M-1970-04,T-54,T-10,3,2,1970
204,M-1970-05,T-06,T-26,3,0,1970

In [25]:
matches_later_1970.shape

(700, 6)

In [61]:
def get_world_cup_match_data(match):
    """ 
    Function to get training example from a world cup match.
    
    Args:
        match: (PandasNamedTuple): A row from the matches_later_1970 dataframe
        
    Returns:
        x_i: (ndarray): A (22,9) ndarray that has the statistics of each player in home and away team
        y_i: (ndarray): A (2,1) ndarray showing result of the match
    """
    x_i = np.empty((0,9))
    # Get players in home team
    
    # Get players in away team
    
    # For each player
    # Get statistics
    # Store in x_i
    
    for i in range(22):
        player_statistics = np.full((1,9), i)
        x_i = np.append(x_i, player_statistics, axis=0)
    
    # Get result
    y_i = np.array([
        [match.home_team_score],
        [match.away_team_score]
    ])
    return (x_i, y_i)

In [73]:
def create_world_cup_match_dataset():
    """ 
    Creates dataset on world cup matches data and saves into a file
    """
    batch_size = 100
    total_matches = matches_later_1970.shape[0]
    total_batches = math.ceil(total_matches / batch_size)
    X = np.empty((0,22,9))
    Y = np.empty((0,2,1))
    
    for i in range(total_batches):
        start = i * batch_size
        if i == total_batches - 1:
            end = total_matches
        else:
            end = start + batch_size
            
        print(f"Processing batch #{i} which goes from row {start} to {end}")
        
        batch_matches = matches_later_1970.iloc[start:end]
        players_list = []
        results_list = []
        
        players_file_name = f"players_batch_{i}_{datetime.now()}"
        results_file_name = f"results_batch_{i}_{datetime.now()}"
        
        for match in batch_matches.itertuples():
            x_i, y_i = get_world_cup_match_data(match=match)
            players_list.append(x_i)
            results_list.append(y_i)
        
        X_b = np.array(players_list)
        Y_b = np.array(results_list)
        X = np.append(X, X_b, axis=0)
        Y = np.append(Y, Y_b, axis=0)
        
        np.save(players_file_name, X)
        np.save(results_file_name, Y)
        
    
create_world_cup_match_dataset()

Processing batch #0 which goes from row 0 to 100
Processing batch #1 which goes from row 100 to 200
Processing batch #2 which goes from row 200 to 300
Processing batch #3 which goes from row 300 to 400
Processing batch #4 which goes from row 400 to 500
Processing batch #5 which goes from row 500 to 600
Processing batch #6 which goes from row 600 to 700

In [77]:
Y = np.load('results_batch_6_2026-05-25 16:28:40.426796.npy')
print(Y)

[[[0.]
  [0.]]

 [[2.]
  [0.]]

 [[1.]
  [0.]]

 ...

 [[2.]
  [1.]]

 [[2.]
  [0.]]

 [[4.]
  [2.]]]